# Generated by Django 5.0.4 on 2024-06-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egreso',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='created',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='desglosar',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='total',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='updated',
        ),
        migrations.AddField(
            model_name='egreso',
            name='numero_carro',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
