# Generated by Django 5.0.4 on 2024-06-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Debito', 'Débito'), ('Credito', 'Crédito')], max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.egreso')),
            ],
        ),
    ]
